name: Terraform

on:
  pull_request:
  push:
    branches:
      - task_1

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  GHA_ROLE: ${{ secrets.GHA_ROLE }}
  REGION: ${{ secrets.REGION }}
  TERRAFORM_VERSION: ${{ secrets.TERRAFORM_VERSION }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create terraform cache
        uses: actions/cache/save@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          
      - name: Terraform Check
        run: terraform fmt

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION  }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.GHA_ROLE }}

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore terraform cache
        uses: actions/cache/restore@v4
        with:
          path: .terraform*
          key: terraform-cache-${{ runner.os }}-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION  }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.GHA_ROLE }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
